import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Web3Modal } from "@/context/Web3Modal";
// import { SessionProvider } from "next-auth/react"
// import type { AppProps } from "next/app"
// import type { Session } from "next-auth"

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <SessionProvider session={session}> */}
          <Web3Modal>
            {children}
          </Web3Modal>
        {/* </SessionProvider> */}
      </body>
    </html>
  )
}
